### ISSUE TITLE
This plugin doesn't work in addressables@1.8.3 

### ISSUE THREAD

**Issue by ambr-kobayashi** [favoyang/unity-addressable-importer#31]
When I update addressables package from 1.2.4 to 1.8.3,
because of modification of class `AddressableAssetEntry`,
this plugin doesn't work.

I don't know when `AddressableAssetEntry.cs` was modified. sorry...
In this modification, variables described in below are added.
```
        [SerializeField]
        private UnityEngine.Object m_MainAsset;
        [SerializeField]
        private UnityEngine.Object m_TargetAsset;
```

Addressables System becomes NOT to work unless fileID and GUID are stored in these variables :(
( Currently, using this plugin, fileID becomes 0 (== these object is null) )

I have little time to fix this issue, because of my hard work...
I wish someone fix this issue, or I'll try to fix it when I have enough time to do it :)

**Comment by favoyang** [comment]
Hi @ambr-kobayashi,

Thanks for reporting the issue. However, I can not reproduce it with 1.8.3. The importer creates AddressableAssetEntry using AddressableAssetSettings.CreateOrMoveEntry, which is the same as the Addressable GUI does. For `m_MainAsset` and `m_TargetAsset`, both are just cached properties and can be re-acquired from runtime.

E.g. the only place that references `m_MainAsset` is via `MainAsset`:
```
        [SerializeField]
        private UnityEngine.Object m_MainAsset;
        /// <summary>
        /// The main asset object for this entry.
        /// </summary>
        public UnityEngine.Object MainAsset
        {
            get
            {
                if (m_MainAsset == null)
                {
                    AddressableAssetEntry e = this;
                    while (string.IsNullOrEmpty(e.AssetPath))
                    {
                        if (e.ParentEntry == null)
                            return null;
                        e = e.ParentEntry;
                    }

                    m_MainAsset = AssetDatabase.LoadMainAssetAtPath(AssetPath);
                }

                return m_MainAsset;
            }
        }
```

**Comment by ambr-kobayashi** [comment]
@favoyang 
Thanks for replying quickly!!
I'll organize how to represent this situation.

**Comment by favoyang** [comment]
@ambr-kobayashi,

Could you reproduce the issue? If not I'm going to close this issue, because the title is a bit misleading.

**Comment by ambr-kobayashi** [comment]
@favoyang 
sorry for re-investigating about this issue.
From the conclusion, your plugin works fine, so this issue should be closed.

Though there are difference of AddressableAssetGroup between adding manually and using this plugin in yaml file.

yaml file becomes like this with manually add addressables to asset groups( using GUI ).
```
m_SerializeEntries:
  - m_GUID: 1960c6e5989d942febb46da7fd71cdc1
    m_Address: asset_001
    m_ReadOnly: 0
    m_SerializedLabels: []
    m_MainAsset: {fileID: 8300000, guid: 1960c6e5989d942febb46da7fd71cdc1, type: 3}
    m_TargetAsset: {fileID: 8300000, guid: 1960c6e5989d942febb46da7fd71cdc1, type: 3}
  - m_GUID: 36e7e2406deee4ebe86c1f635eb36a5f
    m_Address: asset_002
    m_ReadOnly: 0
    m_SerializedLabels: []
    m_MainAsset: {fileID: 8300000, guid: 36e7e2406deee4ebe86c1f635eb36a5f, type: 3}
    m_TargetAsset: {fileID: 8300000, guid: 36e7e2406deee4ebe86c1f635eb36a5f, type: 3}

```


with using this plugin, yaml file becomes like this.
```
  m_SerializeEntries:
  - m_GUID: d5a0e7311d56e46a194fd2ae8de6d3ef
    m_Address: asset_003
    m_ReadOnly: 0
    m_SerializedLabels:
    - LabelTest
    m_MainAsset: {fileID: 0}
    m_TargetAsset: {fileID: 0}
  - m_GUID: f1feb72c825d44c89a1614f8b4f70c1a
    m_Address: asset_004
    m_ReadOnly: 0
    m_SerializedLabels:
    - LabelTest
    m_MainAsset: {fileID: 0}
    m_TargetAsset: {fileID: 0}
```

However, `AddressableAssetEntry.TargetAsset` and `AddressableAssetEntry.MainAsset` are used in ( refered by ) EditorScript only.
Therefore, there is no effect on runtime script.

I apologize about miss reporting and  checking behaviour insufficiently.
